import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>nakaatsu Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Azeret+Mono:wght@700&family=Kosugi+Maru&family=Raleway:wght@400;600&display=swap" rel="stylesheet" />
      </Head>

      <div className={styles.header}>
        <div className={styles.menu}>WORKS</div>
        <div className={styles.menu}>ABOUT</div>
      </div>

      <div className={styles.main}>
        <div className={styles.firstView}>
          <div className={styles.icon}>
            {/* <div className={styles.testIcon}></div> */}
            <Image src="/images/nakaatsu_icon.png" width={400} height={400} objectFit={'contain'} />
          </div>
          <div className={styles.welcome}>Welcome to nakaatsu's site.</div>
        </div>
        <div className={styles.about}>
          <div className={styles.aboutContainer}>
            <div className={styles.aboutTitle}>About</div>
            <div className={styles.aboutDescription}>
              このサイトは nakaatsu のポートフォリオサイトです。<br />
              「ではみなさんは、そういうふうに川だと云いわれたり、乳の流れたあとだと云われたりしていたこのぼんやりと白いものがほんとうは何かご承知ですか。」<br />
              先生は、黒板に吊つるした大きな黒い星座の図の、上から下へ白くけぶった銀河帯のようなところを指さしながら、みんなに問といをかけました。
            </div>
          </div>
        </div>
        <div className={styles.history}>
          <div className={styles.historyTitle}>History</div>
          <div className={styles.historyContainer}>
            <div className={styles.year}>2022.2</div>
            <div className={styles.description}>freee株式会社で働き始めました。</div>
          </div>
          <div className={styles.historyContainer}>
            <div className={styles.year}>2018.9</div>
            <div className={styles.description}>いちから株式会社（現ANYCOLOR株式会社）で働き始めました。</div>
          </div>
          <div className={styles.historyContainer}>
            <div className={styles.year}>2016.4</div>
            <div className={styles.description}>株式会社アルファシステムズで働き始めました。</div>
          </div>
          <div className={styles.historyContainer}>
            <div className={styles.year}>2016.3</div>
            <div className={styles.description}>東京電機大学情報通信工学科を卒業しました。</div>
          </div>
        </div>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
